# SSTPA Tools installer (Windows PowerShell).
#
# - verifies prerequisites (Docker Desktop + Compose v2)
# - copies the packaged payload to the install prefix
# - generates deploy\.env with fresh random passwords (never shipped)
# - loads bundled container images for air-gapped hosts
# - installs the uninstaller and the Windows reference-data loader
#
# The Backend is NOT started here; the Startup Software is the user entry
# point (SRS §4) and performs `docker compose up` on launch.
#
# 2025 Nicholas Triska. All rights reserved. See NOTICE in the payload.
param(
  [string]$Prefix = "$env:LOCALAPPDATA\SSTPA-Tools",
  [switch]$SkipDockerCheck
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Payload = Join-Path $ScriptDir "payload"

if (-not (Test-Path $Payload)) {
  throw "Payload directory not found: $Payload"
}

Write-Host "==> Checking prerequisites"
if (-not $SkipDockerCheck) {
  $Docker = Get-Command docker -ErrorAction SilentlyContinue
  if (-not $Docker) {
    throw "Docker is required but not on PATH. Install Docker Desktop, then re-run install.ps1."
  }
  & docker compose version *> $null
  if ($LASTEXITCODE -ne 0) {
    throw "Docker Compose v2 is required ('docker compose' subcommand not available)."
  }
  & docker info *> $null
  if ($LASTEXITCODE -ne 0) {
    Write-Warning "The Docker daemon is not reachable right now. Installation continues, but Docker Desktop must be running before SSTPA Tools is started."
  }
}

Write-Host "==> Installing payload to $Prefix"
New-Item -ItemType Directory -Force -Path $Prefix | Out-Null
Copy-Item -Path (Join-Path $Payload "*") -Destination $Prefix -Recurse -Force
foreach ($helper in @("uninstall.ps1", "load-reference-data.ps1")) {
  $src = Join-Path $ScriptDir $helper
  if (Test-Path $src) { Copy-Item -Path $src -Destination $Prefix -Force }
}

# Fresh deployment credentials: generated per-installation, never packaged.
$EnvFile = Join-Path $Prefix "deploy\.env"
function New-RandomSecret {
  -join ((1..32) | ForEach-Object { '{0:x}' -f (Get-Random -Maximum 16) })
}
if (Test-Path $EnvFile) {
  Write-Host "==> Keeping existing deployment credentials ($EnvFile)"
} else {
  Write-Host "==> Generating deployment credentials ($EnvFile)"
  $Neo4jPw = New-RandomSecret
  $GrafanaPw = New-RandomSecret
  $Stamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
  @"
# SSTPA Tools deployment environment - generated by install.ps1 $Stamp
# Neo4j bakes its password into the neo4j-data volume on first startup; to
# change it later you must also 'docker compose down -v' (destroys data).
SSTPA_ENV=production

# Neo4j (used by both the neo4j service and the backend service)
SSTPA_NEO4J_PASSWORD=$Neo4jPw

# Grafana admin (dashboards at https://localhost/grafana/)
SSTPA_GRAFANA_USER=admin
SSTPA_GRAFANA_PASSWORD=$GrafanaPw

# Caddy edge ports (host side). Change if 80/443 are already in use locally.
SSTPA_HTTP_PORT=80
SSTPA_HTTPS_PORT=443
"@ | Set-Content -Path $EnvFile -Encoding ascii
}

$ImagesDir = Join-Path $Payload "images"
if (Test-Path $ImagesDir) {
  $Docker = Get-Command docker -ErrorAction SilentlyContinue
  if ($Docker) {
    & docker info *> $null
    if ($LASTEXITCODE -eq 0) {
      Write-Host "==> Loading bundled container images"
      Get-ChildItem -Path $ImagesDir -Filter "*.tar" | Sort-Object Name | ForEach-Object {
        docker load -i $_.FullName
      }
    }
  }
}

Write-Host ""
Write-Host "SSTPA Tools installed to $Prefix"
Write-Host ""
$StartupBin = Join-Path $Prefix "bundles\startup\bin\sstpa-startup.exe"
if (Test-Path $StartupBin) {
  Write-Host "Launch SSTPA Tools:   $StartupBin"
  Write-Host "  (starts the Backend, authenticates you - first run creates the"
  Write-Host "   RootAdmin account - then opens the GUI; stops the Backend on exit)"
} else {
  Write-Host "Startup binary for this platform was not bundled; start manually:"
  Write-Host "  cd `"$Prefix\deploy`"; docker compose up -d"
}
$ReferenceDir = Join-Path $Prefix "reference-data"
if (Test-Path $ReferenceDir) {
  $ReferenceArtifact = Get-ChildItem -Path $ReferenceDir -Filter "sstpa-ref-data-*.tar.gz" | Sort-Object Name | Select-Object -Last 1
  if ($ReferenceArtifact) {
    Write-Host ""
    Write-Host "Reference data artifact: $($ReferenceArtifact.FullName)"
    Write-Host "Load it once the Backend is healthy:"
    Write-Host "  powershell -File `"$Prefix\load-reference-data.ps1`" -Artifact `"$($ReferenceArtifact.FullName)`" -DeployDir `"$Prefix\deploy`""
  }
}
Write-Host ""
Write-Host "Uninstall: powershell -File `"$Prefix\uninstall.ps1`""
