// Package telemetry wires OpenTelemetry traces/metrics and Prometheus
// instrumentation for the SSTPA Backend (SRS §5.6.2–§5.6.4).
//
// 2025 Nicholas Triska. All rights reserved. See NOTICE at repository root.
package telemetry

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"strconv"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.41.0"
	"go.opentelemetry.io/otel/trace"
)

// Metrics holds the Prometheus instruments exposed at /metrics (SRS §5.6.3).
type Metrics struct {
	RequestsTotal          *prometheus.CounterVec
	RequestDuration        *prometheus.HistogramVec
	RequestsInFlight       prometheus.Gauge
	GraphTransactionsTotal *prometheus.CounterVec
	OwnershipNotifications prometheus.Counter
}

// NewMetrics registers SSTPA metrics on the default Prometheus registry.
func NewMetrics() *Metrics {
	return &Metrics{
		RequestsTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "sstpa_http_requests_total",
			Help: "Total HTTP requests by method, path pattern and status.",
		}, []string{"method", "path", "status"}),
		RequestDuration: promauto.NewHistogramVec(prometheus.HistogramOpts{
			Name:    "sstpa_http_request_duration_seconds",
			Help:    "HTTP request latency.",
			Buckets: prometheus.DefBuckets,
		}, []string{"method", "path"}),
		RequestsInFlight: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "sstpa_http_requests_in_flight",
			Help: "Current number of in-flight HTTP requests.",
		}),
		GraphTransactionsTotal: promauto.NewCounterVec(prometheus.CounterOpts{
			Name: "sstpa_graph_transactions_total",
			Help: "Neo4j transactions by outcome (commit|rollback).",
		}, []string{"outcome"}),
		OwnershipNotifications: promauto.NewCounter(prometheus.CounterOpts{
			Name: "sstpa_ownership_notifications_total",
			Help: "CHANGE_NOTIFICATION messages generated by commits (SRS §5.6.6.8.1).",
		}),
	}
}

// MetricsHandler returns the Prometheus scrape handler.
func MetricsHandler() http.Handler { return promhttp.Handler() }

// InitTracer configures the OTLP gRPC trace exporter to the OTel Collector.
// Returns a shutdown func. If endpoint is empty, tracing is a no-op.
func InitTracer(ctx context.Context, endpoint, serviceName, version string) (func(context.Context) error, error) {
	if endpoint == "" {
		slog.Info("telemetry: OTLP endpoint not configured; traces disabled")
		return func(context.Context) error { return nil }, nil
	}
	exp, err := otlptracegrpc.New(ctx,
		otlptracegrpc.WithEndpoint(endpoint),
		otlptracegrpc.WithInsecure(),
	)
	if err != nil {
		return nil, fmt.Errorf("create OTLP exporter: %w", err)
	}
	res, err := resource.Merge(resource.Default(), resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceName(serviceName),
		semconv.ServiceVersion(version),
	))
	if err != nil {
		return nil, err
	}
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exp),
		sdktrace.WithResource(res),
	)
	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(
		propagation.TraceContext{}, propagation.Baggage{}))
	return tp.Shutdown, nil
}

// Tracer returns the SSTPA backend tracer.
func Tracer() trace.Tracer { return otel.Tracer("sstpa-backend") }

// HTTPMiddleware instruments each request with metrics and a span
// (SRS §5.7.5 telemetry flow).
func (m *Metrics) HTTPMiddleware(routePattern func(*http.Request) string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			start := time.Now()
			m.RequestsInFlight.Inc()
			defer m.RequestsInFlight.Dec()

			ctx, span := Tracer().Start(r.Context(), r.Method+" "+r.URL.Path)
			defer span.End()

			sw := &statusWriter{ResponseWriter: w, status: http.StatusOK}
			next.ServeHTTP(sw, r.WithContext(ctx))

			path := routePattern(r)
			m.RequestsTotal.WithLabelValues(r.Method, path, strconv.Itoa(sw.status)).Inc()
			m.RequestDuration.WithLabelValues(r.Method, path).Observe(time.Since(start).Seconds())
		})
	}
}

type statusWriter struct {
	http.ResponseWriter
	status int
}

func (w *statusWriter) WriteHeader(code int) {
	w.status = code
	w.ResponseWriter.WriteHeader(code)
}
